### ISSUE TITLE
Bug when reading the directory

### ISSUE THREAD

**Issue by mkslack** [xahmol/GeoUTools#3]
Hi...

there seem to be a bug in the Readdir function:

```
// Initialise reading dir
    enableIO();
    uii_open_dir();
    uii_get_dir();
    restoreIO();

    // Loop while dir data is available or memory is full
    while(uii_isdataavailable())

```
I/O is turned off (through restoreIO) but while(uii_isdataavailable) reads the statusreg from the I/O space. This will work for GEOS128, but not for GEOS64, where I/O space is always off. That's why enableIO/restoreIO is required.

Currently that worked for MP3-64 because when uii_isdataavailable reads the byte from $df1c from RAM (not from I/O) it will get $de. There is Bit%7 is always set = Data available.

For GDOS64 (successor of MP3-64) this would read $10 from $df1c (RAM) where Bit%7 is cleared (No data available). This results in an always empty directory and a freeze of "ROOT" and "HOME" icon because the ultimate is left in a bad state after reading the directory. Since while-Loop would never be executed the ultimate is still in "Data available" state and since there is no uii_abort for this case "ROOT" and "HOME" icon will cause the system to freeze. 

In my opinion there should be some extra code if while-Loop will not be executed which will send abort to the ultimate bevor continue.

I think this might also be the reason for your "Fix" comment in mount.c in Readdir.

**Comment by xahmol** [comment]
Many thanks! This bug was driving me crazy: working on C128 and not working on C64. Indeed, the fix that you spotted was exactly for this reason.

You have not only spotted the bug, but also explained the why it worked on C128.
Stupid, never realised that I actually was calling a function that needed IO as part of that while condition.

Fixed it now: https://github.com/xahmol/GeoUTools/commit/8f81cbf31a61a3415834118031a731ee5eab8cfd
New build: https://github.com/xahmol/GeoUTools/raw/main/GeoUTools-v01-20230407-2252.zip

It now does not need the fix anymore, works now without the original fix on GEOS64, MP3 64, GEOS128 and MP3 128 at my machines. Please confirm it is also working on your side.

**Comment by markusC64** [comment]
Works for me now on GDOS64.

**Comment by mkslack** [comment]
> Please confirm it is also working on your side.

I can not confirm that myself since me is using an older Firmware without DEVINFO, but i trust in markusC64 testing it.

Issue can be closed now.
